# .air.toml
root = "."
tmp_dir = "tmp"

[build]
  cmd = "go build -o ./tmp/main.exe ."
  bin = "tmp\\main.exe"
  
  # Observar también archivos de configuración YAML
  include_ext = ["go", "tpl", "tmpl", "html", "yaml"]
  exclude_dir = ["assets", "tmp", "vendor", "testdata", "docs"]
  exclude_regex = ["_test.go"]
  
  # Activar cierre limpio (graceful shutdown)
  send_interrupt = true
  kill_delay = "500ms"
  
  # Detener si la compilación falla
  stop_on_error = true

[color]
  build = "yellow"
  main = "magenta"
  runner = "green"
  watcher = "cyan"

[log]
  # Añadir timestamp a los logs
  time = true

[misc]
  # Limpiar el binario temporal al salir
  clean_on_exit = true

[screen]
  # Limpiar la consola en cada reinicio para una vista más limpia
  clear_on_rebuild = true
